name: gbt_fluent2_ui
description: A robust Fluent2 Material-based design system for seamless and intuitive user experiences.
version: 6.0.0
repository: https://github.com/grbtec/gbt_fluent2_ui


environment:
  sdk: ^3.4.0
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  fluentui_system_icons: ^1.1.223

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0

flutter:
  uses-material-design: true


